DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
CREATE TABLE BOOKS
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    BOOKTITLE VARCHAR(255) NOT NULL,
    AUTHORID  VARCHAR(255) NOT NULL,
    GENREID   VARCHAR(255) NOT NULL
);
CREATE TABLE AUTHORS
(
    ID       BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    FULLNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL
);
CREATE TABLE GENRES
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    GENRENAME VARCHAR(255) NOT NULL
);
