DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
CREATE TABLE BOOKS
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    BOOK_TITLE VARCHAR(255) NOT NULL,
    AUTHOR_ID  VARCHAR(255) NOT NULL,
    GENRE_ID   VARCHAR(255) NOT NULL
);
CREATE TABLE AUTHORS
(
    ID       BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    FULL_NAME VARCHAR(255) NOT NULL
);
CREATE TABLE GENRES
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    GENRE_NAME VARCHAR(255) NOT NULL
);
