DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE BOOKS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    BOOK_TITLE VARCHAR(255)                      NOT NULL,
    AUTHOR_ID  VARCHAR(255)                      NOT NULL,
    GENRE_ID   VARCHAR(255)                      NOT NULL
);
CREATE TABLE AUTHORS
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    FULL_NAME VARCHAR(255)                      NOT NULL
);
CREATE TABLE GENRES
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    GENRE_NAME VARCHAR(255)                      NOT NULL
);
CREATE TABLE COMMENTS
(
    ID      BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    book_id VARCHAR(255)                      NOT NULL,
    comment VARCHAR(555)                      NOT NULL

);
CREATE TABLE USERS
(
    ID            BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    USER_NAME     VARCHAR(255)                      NOT NULL,
    USER_PASSWORD VARCHAR(255)                      NOT NULL,
    IS_ENABLED    BOOLEAN                           NOT NULL,
    ROLE_ID       VARCHAR(255)                      NOT NULL
);
CREATE TABLE ROLES
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ROLE_TYPE VARCHAR(255)                      NOT NULL
);