spring:
  shell:
  #    interactive:
  #      enabled: true

  data:
    mongodb:
      database: testdb
      port: 27017

mongock:
  #  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.library.changelogs

logging:
  level:
    ru.quizapp: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"